### ISSUE TITLE
Improve `attribute_updated` in cluster handlers

### ISSUE THREAD

**Issue by TheJulianJES** [zigpy/zha#126]
The `attribute_updated` stuff in the cluster handlers should be improved. There's some duplicate code that can be avoided and it's one of the last places where the old `_value_attribute` stuff is still used.
It's also a bit confusing if only one attribute change actually emits an "attribute updated" event on a cluster. Maybe we should always emit the events and just check for the attribute in the places where we're subscribing? (the config switches do this already) It shouldn't cause any performance issues really..

**Comment by dmulcahey** [comment]
potential areas for remediation:

- DoorLockClusterHandler - attribute_updated - shouldn't be needed and is only updating a single attribute.
- LevelControlClusterHandler - attribute_updated - shouldn't be needed and is only updating a single attribute and we are translating this to a different event. This is a remnant from old light handling code
- OnOffClusterHandler - attribute_updated - shouldn't be needed and is only updating a single attribute 
- FanClusterHandler - attribute_updated - shouldn't be needed and is only updating a single attribute.
- ThermostatClusterHandler - just duplicate code?
- SmartThingsAccelerationClusterHandler - attribute_updated - only updating a single attribute + also sending an event
- IASZoneClusterHandler - attribute_updated - shouldn't be needed and is only updating a single attribute.

**Comment by dmulcahey** [comment]
Looks like protections for the correct attribute were already in all of the subscribers. I have a draft PR up to clean this up.
