### ISSUE TITLE
Valve device switch.id_on_off is not set in switch entity

### ISSUE THREAD

**Issue by claudegel** [zigpy/zha#157]
Since last HA update 2024.8.0, Sinopé  valve devices lost there on/off switch. valve device are loaded by sinope quirks in switch.py.
We can't open or close the valve since the update.
There are only bynary_sensor and sensor that are created for the valve,
There should be a switch.valve_id_on_off created to be able to open and close the valve

**Comment by dmulcahey** [comment]
Put zha in debug mode please and reload the integration. Once everything has loaded disable debug mode and attach the log here.

**Comment by claudegel** [comment]
here are the debug data, device signature and what is showing up in ZHA
[home-assistant.log](https://github.com/user-attachments/files/16570361/home-assistant.log)
![zha-valve](https://github.com/user-attachments/assets/13894756-d118-409e-89c3-cea50c4c4810)
[valve signature.txt](https://github.com/user-attachments/files/16570362/valve.signature.txt)
The valve was not in ZHA prior to HA update to 2024.8.0. Many users complained that switch.valve_on_off has dissapeared.
I've added mine to see that on/off is not available.
Could it be because the valve "device_type": "0x0003", is LEVEL_CONTROLLABLE_OUTPUT and is associated with platform COVER

**Comment by puddly** [comment]
> The valve was not in ZHA prior to HA update to 2024.8.0. 

Do you mean that this device was not working in 2024.7.4?

**Comment by claudegel** [comment]
My device was not connected to ZHA in 2024.7.4 but is was prior of that and was working with an on/off switch. I had removed it because, as a developper for many HA custom_component, I had to test it with those other components. But many other users reported that there valve, same of mine, has just stopped working with HA 2024.8.0 and was ok with 2024.7.4

**Comment by claudegel** [comment]
I've made the quirks for that valve and all other Sinopé valves models and it was working ok for all of them.
Could be nice to have a valve platform in ZHA as is it in HA by the way.

**Comment by puddly** [comment]
Can you post the full log file?

**Comment by TheJulianJES** [comment]
With a quirk, can you change the device type in the replacement to something like "smart plug" or "on off switch"?

**Comment by claudegel** [comment]
I'll try this on off switch

**Comment by claudegel** [comment]
Log with smart plug, no change
[with-smartplug.log](https://github.com/user-attachments/files/16570611/with-smartplug.log)

**Comment by claudegel** [comment]
With ON_OFF_SWITCH. no changes
[with-onoff-switch.log](https://github.com/user-attachments/files/16570623/with-onoff-switch.log)

**Comment by dmulcahey** [comment]
can I have one full debug log without any changes from what is in core today please? Don't filter anything out and make sure all zha loggers are set to debug (easiest is to put zha in debug mode then reload the integration). I want to see the actual discovery output for the device when the entity matching happens. 

thanks!

**Comment by dmulcahey** [comment]
My guess is that if you put zha in full debug mode you will have something like this:

https://github.com/home-assistant/core/issues/123387#issuecomment-2282254783

**Comment by claudegel** [comment]
There is an update HA 2024.8.1 do you want the log before that one? How do you reload ZHA without restarting HA ?

**Comment by claudegel** [comment]
OK find it

**Comment by claudegel** [comment]
[HA-Full.log](https://github.com/user-attachments/files/16570746/HA-Full.log)

**Comment by claudegel** [comment]
device in log is [0x05d7:1:0x0000] Attribute id: 5 value: VA4220ZB

**Comment by dmulcahey** [comment]
2024-08-10 15:55:18.003 DEBUG (MainThread) [zha.application.platforms] Not registering entity <zha.application.platforms.switch.Switch object at 0x7f237e3ad0>, unique id '50:0b:91:40:00:03:ed:b0-1-6' already exists: <zha.application.platforms.binary_sensor.Opening object at 0x7f23974a40>

yep it is there. Thanks!

**Comment by claudegel** [comment]
In the log for the valve I see from cache[True]
For other switch device it is from cache[False]
Is it something relevant?

**Comment by puddly** [comment]
@claudegel Could you attach your `/config/zigbee.db` file (you may need to ZIP it first)? You can also email it to me (`puddly3@gmail.com`).

It should contain everything necessary to figure out why this specific device is behaving this way in 2024.8.0 and not in 2024.7.x.

**Comment by dmulcahey** [comment]
can you attach the device diagnostics to this too

**Comment by claudegel** [comment]
OK will send. I've found in core.entity_registry in the section deleted entities the info about the on_off switch for that same valve. This is from when the valve was on ZHA few month ago.
      {"config_entry_id":"ec2e648309cb49bc91a2b449b2f91933","created_at":"1970-01-01T00:00:00+00:00","entity_id":"switch.sedna2_commutateur","id":"d59c7b93b83312767084c0045200dd1e","modified_at":"1970-01-01T00:00:00+00:00","orphaned_timestamp":null,"platform":"zha","unique_id":"50:0b:91:40:00:03:ed:b0-1-6"},

Here is the db file
[bd.zip](https://github.com/user-attachments/files/16570941/bd.zip)
where do you get the device diagnostics?

**Comment by TheJulianJES** [comment]
The following comment describes how you can get device diagnostics: https://github.com/home-assistant/core/issues/123387#issuecomment-2282280266
Although @dmulcahey seems to have found the issue after much investigation. There's a unique ID collision in ZHA that should not be an issue, but currently is.

**Comment by claudegel** [comment]
diagnostic file
[diagnostic.json](https://github.com/user-attachments/files/16570952/diagnostic.json)

**Comment by claudegel** [comment]
Can I update HA to 2024.8.1 or better waiting in case you need something else.

**Comment by TheJulianJES** [comment]
You can update just fine. It includes a few ZHA bugfixes, but nothing for this yet.
We seem to have everything needed now. And thanks for your answers!

**Comment by claudegel** [comment]
Thnak s a lot. Will wait for the update. feel free to ask if you need anything else.
