### ISSUE TITLE
Orvibo motion sensor SN10ZW not recognized by ZHA

### ISSUE THREAD

**Issue by GammaTek** [zigpy/zha#214]
## Expected behavior
- Orvibo motion sensor can be paired to ZHA Zigbee network (compatibility reported by [Device Compatibility Repository](https://zigbee.blakadder.com/Orvibo_SN10ZW.html))
- Device is displayed as Orvibo motion sensor in ZHA
- Detection is displayed when sensor is triggered
## Actual behavior
- Pairing reported successful
- Motion detection entity created in HA
- Device _not_ recognized as Orvibo motion sensor (or any other device, see signature)
- Motion detection always displayed as triggered in HA (irrespective of sensor activity)
## Attempted solutions
- Reproduction of error in different device of same model
- Unbinding and re-pairing of device (4 attempts) --> No change in behavior
- Re-configuring of device through HA after waking up --> "Reconfigure success" displayed. No entries in "Reporting" column displayed
- Replacement of batteries --> No change in behavior
## Device Signature (non-working, current state)
```
{
  "node_descriptor": {
    "logical_type": 2,
    "complex_descriptor_available": 0,
    "user_descriptor_available": 0,
    "reserved": 0,
    "aps_flags": 0,
    "frequency_band": 8,
    "mac_capability_flags": 128,
    "manufacturer_code": 0,
    "maximum_buffer_size": 80,
    "maximum_incoming_transfer_size": 160,
    "server_mask": 0,
    "maximum_outgoing_transfer_size": 160,
    "descriptor_capability_field": 0
  },
  "endpoints": {
    "1": {
      "profile_id": "0x0104",
      "device_type": "0x0402",
      "input_clusters": [
        "0x0000",
        "0x0001",
        "0x0003",
        "0x0500"
      ],
      "output_clusters": [
        "0x0003"
      ]
    }
  },
  "manufacturer": "欧瑞",
  "model": "585fdfb8c2304119a2432e9845cf2623",
  "class": "zigpy.device.Device"
}
```

**Comment by puddly** [comment]
Please fill out the issue template here: https://github.com/zigpy/zha-device-handlers/. If the device isn't standards-compliant, this isn't an issue with ZHA and the specific device needs to be reverse engineered.
