### ISSUE TITLE
Can't update heating/cooling setpoint of thermostat

### ISSUE THREAD

**Issue by Masy** [zigpy/zha#258]
i've have set the temperature range to 17° - 30°, yet for some reason if i set the temperature to anything but 17, i get the following error:

```py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/zha/helpers.py", line 1286, in handler
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/zha/climate.py", line 230, in async_set_temperature
    await self.entity_data.entity.async_set_temperature(
  File "/usr/local/lib/python3.12/site-packages/zha/application/platforms/climate/__init__.py", line 462, in async_set_temperature
    await self._thermostat_cluster_handler.async_set_heating_setpoint(
  File "/usr/local/lib/python3.12/site-packages/zha/zigbee/cluster_handlers/hvac.py", line 286, in async_set_heating_setpoint
    await self.write_attributes_safe({attr: temperature})
  File "/usr/local/lib/python3.12/site-packages/zha/zigbee/cluster_handlers/__init__.py", line 624, in write_attributes_safe
    raise ZHAException(
zha.exceptions.ZHAException: Failed to write attribute occupied_heating_setpoint=2150: <Status.INVALID_VALUE: 135>
```

The interface displays the range correctly:
![grafik](https://github.com/user-attachments/assets/576fdd79-a02e-47d4-ae37-44131c709989)
![grafik](https://github.com/user-attachments/assets/23e999f7-637a-48c6-b64f-29203e1d30ff)

**Comment by puddly** [comment]
Please upload a debug log and diagnostics JSON for your device.

**Comment by Masy** [comment]
after some debugging the problem seems to be when i initialize the zigbee stack with an already set occupied heat/cool setpoint. So when i start the microcontroller, i read the status of the device and which temperature it is currently set to, and set OCCUPIED_COOLING_SETPOINT_ID and OCCUPIED_HEATING_SETPOINT_ID to the read temperature. If i don't do that, it seems to work fine. However, then HA might be out of sync with the actual setpoint of the AC until it is updated via the interface.

[home-assistant_zha_2024-10-24T11-49-46.844Z.log](https://github.com/user-attachments/files/17506316/home-assistant_zha_2024-10-24T11-49-46.844Z.log)
[zha-3da5f89364f2b930116be3c470048f04-enktro ACmidea-2a8cfe24fc1c66e93d0fdd676fbef0cd.json](https://github.com/user-attachments/files/17506317/zha-3da5f89364f2b930116be3c470048f04-enktro.ACmidea-2a8cfe24fc1c66e93d0fdd676fbef0cd.json)

**Comment by Masy** [comment]
never mind, home assistant just seems to randomly decide what the limit will be, regardless of whether i pre-configure the setpoints or not. it will randomly send garbage as system mode as well if i switch between modes too quickly, like 0x903 (zigbee has defined 0x00-0x09) and start to lag.

**Comment by puddly** [comment]
> it will randomly send garbage as system mode as well if i switch between modes too quickly, like 0x903

You gotta upload some debug logs if you're building your own device like this.

**Comment by Masy** [comment]
the garbage system mode "home assistant sends" me seems to be an issue with the way the ESP SDK defines the enum. i receive a pointer to the value in the callback, which is 1 byte in size, but when i cast the void* to the enum *, it will read more than 1 byte, since the enum is not defined to be 1 byte, but just the default "int". i assume thats why i sometimes receive values like 0x0904 altough i should read 0x04 when i set the mode to heat.
i will just copy the value instead of casting the pointer

**Comment by Masy** [comment]
> after some debugging the problem seems to be when i initialize the zigbee stack with an already set occupied heat/cool setpoint. So when i start the microcontroller, i read the status of the device and which temperature it is currently set to, and set OCCUPIED_COOLING_SETPOINT_ID and OCCUPIED_HEATING_SETPOINT_ID to the read temperature. If i don't do that, it seems to work fine. However, then HA might be out of sync with the actual setpoint of the AC until it is updated via the interface.
> 
> [home-assistant_zha_2024-10-24T11-49-46.844Z.log](https://github.com/user-attachments/files/17506316/home-assistant_zha_2024-10-24T11-49-46.844Z.log) [zha-3da5f89364f2b930116be3c470048f04-enktro ACmidea-2a8cfe24fc1c66e93d0fdd676fbef0cd.json](https://github.com/user-attachments/files/17506317/zha-3da5f89364f2b930116be3c470048f04-enktro.ACmidea-2a8cfe24fc1c66e93d0fdd676fbef0cd.json)

in the diagnostics of the device you can see that the absolute limits are set to 1700 and 3000 for both heating and cooling. yet, in the debug log of home assistant, you can see it fails to set the value to 2750, which is well withing the range of the defined limits. i can't figure out where [self.write_attributes](https://github.com/zigpy/zha/blob/927e249134c87bd7805139c8fb61e048593ec155/zha/zigbee/cluster_handlers/__init__.py#L614) comes from though, then i could see which limits are used to validate if the new value is in the supported range.

**Comment by Masy** [comment]
i get the feeling that thermostat devices just aren't fully supported in zha. I can't even update the temperature setpoint from the device. I've send a write attribute command, which home assistant received:
```
2024-10-28 13:25:50.761 DEBUG (MainThread) [zigpy.zcl] [0xA14F:1:0x0201] Decoded ZCL frame: Thermostat:Write_Attributes(attributes=[Attribute(attrid=0x0012, value=TypeValue(type=int16s, value=2500))])
2024-10-28 13:25:50.764 DEBUG (MainThread) [zigpy.zcl] [0xA14F:1:0x0201] Received command 0x02 (TSN 8): Write_Attributes(attributes=[Attribute(attrid=0x0012, value=TypeValue(type=int16s, value=2500))])
```
But it wasn't updated. When i read the attribute via the interface i get back 2100, which was the value before i send the update.

**Comment by puddly** [comment]
> I've send a write attribute command, which home assistant received

This is backwards. Your device has a Thermostat cluster with attributes and ZHA will write those attributes to control the device. ZHA doesn't have a Thermostat cluster, you can't send it a `Write_Attributes` command and expect it to do anything.

If you change an attribute you need to send an attribute report, not write an attribute.

> i get the feeling that thermostat devices just aren't fully supported in zha.

You're building your own custom device. I suggest you revisit the ZCL spec, this isn't a problem with ZHA.
