### ISSUE TITLE
Issue with Zigbee Mesh network with > 31 devices

### ISSUE THREAD

**Issue by ummarbhutta** [zigpy/zha#315]
Hi All,

I am using Home Assistant for home automation. I have combination of routers (mostly) and end devices, and so far the network has been quite stable in performance (95% + time it is very responsive) till overall device count is <= 31. The problem start showing when I tried to add 32nd device to network (a router device from SONOFF), that took so long to get configured, HA always trying with different NWK but never worked, although finally it worked. But now I have tried to add 33rd device (End device from Tuya), it is discovered quickly but never get configured successfully. Seems like something is stopping from network to grow, but not sure what it is. Not my all devices are connected to Coordinator directly, as most of devices are router and mesh shown on network visualization tab looks fairly complex. Following are details of system:

**HA Setup**

1. Core: **2024.9.1**
2. Frontend: **20240906.0**
3. Docker based installation
4. RPi 4 with Raspbian

**Devices Stats**

1. Total devices: **32**
2. Routers: **23**
5. End devices: **8**
6. & one coordinator
7. Coordinator: **SONOFF TI CC2652 Based**
8. Coordinator FW: **Z-Stack 20210708** _(Seems like an older one, could that be a reason? Looks like there is a new release [here](https://github.com/Koenkk/Z-Stack-firmware/blob/master/coordinator/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_other_coordinator_20240710.zip), but haven't tried it yet)_

**Mesh network**

![image](https://github.com/user-attachments/assets/bf2320b9-7665-464d-8410-32bb5a62f3ca)

**Direct connection to Coordinator**
Only 4 devices directly connected to coordinator, as shown in following picture.
![image](https://github.com/user-attachments/assets/4d15f81c-32cd-4efe-80f9-24afc03765d8)

**Procedure of adding new device**
I usually add devices by going to Settings > Devices & services > Zigbee Home Automation > Clicking "Add Device" on bottom right. Not sure whether this strategy uses coordinator to add device already or picks the closest router by default (I believe so, because I have added device very far from coordinator but close to router and it works)

**Current situation**

I am unable to add any additional device to network, ideally it shouldn't be the case.

Any help/clue in this regard is appreciated. My only guess is about FW of coordinator, but not sure if this is really an issue.

**Comment by puddly** [comment]
Upgrade your firmware, make sure your coordinator is on a USB extension cable, and moved away from interference sources such as USB 3.0 ports, SSDs, and WiFi routers.

**Comment by ummarbhutta** [comment]
Thanks @puddly , 

- Already using USB extension cable.
- Have reasonable distance from RPi and WiFi Router, RPi itself is connected via LAN cable to main router.
- Will upgrade firmware of coordinator and update the thread.

**Comment by ummarbhutta** [comment]
Update:

I updated the firmware to **Z-Stack 20240710**, and overall system seems to be much stable now, and I can add more than 31 devices now. 

![image](https://github.com/user-attachments/assets/6555fcfb-6a31-4d9d-aeaf-4758ad4643a7)


Closing this issue.
